// Example DAX user-defined functions (Power BI Desktop / Service,
// June 2026 GA release onward). No Python or M numerics needed here --
// just DAX operating on small tables already loaded into the model.

// =================================================================
// IMPORTANT: DAX has no native ATAN2 function (unlike Excel or M),
// despite several of the formulas below needing one. This is a
// small, standard workaround (the same pattern used throughout the
// Power BI community for this) that every other function here calls
// internally.
// =================================================================
DEFINE
/// Replicates atan2(y, x) since DAX has no built-in equivalent.
/// @param {NUMERIC} Y
/// @param {NUMERIC} X
/// @returns Angle in radians, -pi to pi
FUNCTION Atan2 = (
    Y : NUMERIC,
    X : NUMERIC
) =>
    SWITCH(
        TRUE(),
        X > 0, ATAN(Y / X),
        X < 0 && Y >= 0, ATAN(Y / X) + PI(),
        X < 0 && Y < 0, ATAN(Y / X) - PI(),
        X = 0 && Y > 0, PI() / 2,
        X = 0 && Y < 0, 0 - PI() / 2,
        BLANK()
    )


// =================================================================
// BEFORE YOU CAN USE TidalForecast BELOW:
// =================================================================
// This function reconstructs a tide from known harmonic constituents
// (frequency, amplitude, phase per constituent, e.g. M2, S2, K1, O1).
// It does NOT derive those constituents from raw data -- fitting them
// requires a least-squares solve, which isn't practical in DAX or M.
//
// So before this UDF is usable, you need a small `Constituents` table
// with columns: Frequency_cph, Amplitude, Phase_deg. Get that table
// one of two ways:
//
//   1. Published constituents for a real station -- e.g. NOAA CO-OPS
//      (US stations, freely available via their API/website) or
//      UKHO/Admiralty tide tables (UK stations). Pull the values once
//      and load them as a static table.
//   2. A one-off harmonic fit done outside Power BI -- e.g. if you
//      still have old MATLAB T_TIDE/UTide output from university, or
//      ask someone to run the fit once in Python/R/MATLAB -- and load
//      just the resulting amplitude/phase/frequency table here.
//
// Either way, this UDF only ever needs that small table as input --
// never the raw time series, and never Python at query time.
// =================================================================

DEFINE
/// Reconstructs tide height at a given number of hours since t0,
/// from a loaded constituent table.
/// @param {NUMERIC} HoursSinceT0 - elapsed hours since the reference time
/// @param {NUMERIC} MeanLevel - constant offset (e.g. Z0 / mean sea level)
/// @returns Reconstructed elevation
FUNCTION TidalForecast = (
    HoursSinceT0 : NUMERIC,
    MeanLevel : NUMERIC = 0
) =>
    MeanLevel +
    SUMX(
        Constituents,
        [Amplitude] *
        COS(
            2 * PI() * [Frequency_cph] * HoursSinceT0
            - RADIANS([Phase_deg])
        )
    )

EVALUATE
{ TidalForecast(6.2, 0) }  // example: elevation 6.2 hours after t0


// ---------------------------------------------------------------
// Simplified density lookup (same formula as fn_ApproxDensity.m) --
// use whichever of the DAX or M version fits where you need it in
// your model/query.
// ---------------------------------------------------------------
DEFINE
/// Rough linearised seawater density estimate (kg/m^3).
/// @param {NUMERIC} TemperatureC - in-situ temperature, deg C
/// @param {NUMERIC} SalinityPSU - practical salinity
/// @returns Approximate density, kg/m^3
FUNCTION ApproxDensity = (
    TemperatureC : NUMERIC,
    SalinityPSU : NUMERIC
) =>
    1000
    + 0.78 * SalinityPSU
    - 0.20 * TemperatureC
    - 0.0055 * POWER(TemperatureC, 2)

EVALUATE
{ ApproxDensity(12, 35) }


// ---------------------------------------------------------------
// Mackenzie sound speed (same formula as fn_SoundSpeedMackenzie.m)
// ---------------------------------------------------------------
DEFINE
/// Mackenzie (1981) empirical speed of sound in seawater (m/s).
/// @param {NUMERIC} TemperatureC
/// @param {NUMERIC} SalinityPSU
/// @param {NUMERIC} DepthM
/// @returns Speed of sound, m/s
FUNCTION SoundSpeedMackenzie = (
    TemperatureC : NUMERIC,
    SalinityPSU : NUMERIC,
    DepthM : NUMERIC
) =>
    1448.96
    + 4.591 * TemperatureC
    - 5.304E-2 * POWER(TemperatureC, 2)
    + 2.374E-4 * POWER(TemperatureC, 3)
    + 1.340 * (SalinityPSU - 35)
    + 1.630E-2 * DepthM
    + 1.675E-7 * POWER(DepthM, 2)
    - 1.025E-2 * TemperatureC * (SalinityPSU - 35)
    - 7.139E-13 * TemperatureC * POWER(DepthM, 3)

EVALUATE
{ SoundSpeedMackenzie(12, 35, 100) }


// ---------------------------------------------------------------
// Great-circle distance between two lat/lon points (Haversine).
// Uses the Atan2 helper defined above -- DAX has no native ATAN2.
// ---------------------------------------------------------------
DEFINE
/// Great-circle distance between two lat/lon points (Haversine formula).
/// @param {NUMERIC} Lat1 - latitude of point 1, decimal degrees
/// @param {NUMERIC} Lon1 - longitude of point 1, decimal degrees
/// @param {NUMERIC} Lat2 - latitude of point 2, decimal degrees
/// @param {NUMERIC} Lon2 - longitude of point 2, decimal degrees
/// @returns Distance in metres
FUNCTION HaversineDistance = (
    Lat1 : NUMERIC,
    Lon1 : NUMERIC,
    Lat2 : NUMERIC,
    Lon2 : NUMERIC
) =>
    VAR EarthRadiusM = 6371000
    VAR Phi1 = RADIANS(Lat1)
    VAR Phi2 = RADIANS(Lat2)
    VAR DeltaPhi = RADIANS(Lat2 - Lat1)
    VAR DeltaLambda = RADIANS(Lon2 - Lon1)
    VAR A =
        SIN(DeltaPhi / 2) * SIN(DeltaPhi / 2)
        + COS(Phi1) * COS(Phi2) * SIN(DeltaLambda / 2) * SIN(DeltaLambda / 2)
    VAR C = 2 * Atan2(SQRT(A), SQRT(1 - A))
    RETURN
        EarthRadiusM * C

EVALUATE
{ HaversineDistance(53.4808, -2.2426, 51.5074, -0.1278) }  // Manchester to London, ~262 km


// ---------------------------------------------------------------
// Initial bearing (forward azimuth) from point 1 to point 2, in
// degrees from true north (0-360). Pairs with HaversineDistance --
// distance tells you how far, this tells you which direction.
// ---------------------------------------------------------------
DEFINE
/// Initial bearing from point 1 to point 2, degrees from true north.
/// @param {NUMERIC} Lat1
/// @param {NUMERIC} Lon1
/// @param {NUMERIC} Lat2
/// @param {NUMERIC} Lon2
/// @returns Bearing in degrees, 0-360
FUNCTION InitialBearing = (
    Lat1 : NUMERIC,
    Lon1 : NUMERIC,
    Lat2 : NUMERIC,
    Lon2 : NUMERIC
) =>
    VAR Phi1 = RADIANS(Lat1)
    VAR Phi2 = RADIANS(Lat2)
    VAR DeltaLambda = RADIANS(Lon2 - Lon1)
    VAR Y = SIN(DeltaLambda) * COS(Phi2)
    VAR X = COS(Phi1) * SIN(Phi2) - SIN(Phi1) * COS(Phi2) * COS(DeltaLambda)
    VAR ThetaDeg = DEGREES(Atan2(Y, X))
    RETURN
        MOD(ThetaDeg + 360, 360)

EVALUATE
{ InitialBearing(53.4808, -2.2426, 51.5074, -0.1278) }  // ~146 degrees (SE)


// ---------------------------------------------------------------
// Destination point: given a start point, bearing, and distance,
// where do you end up. The reverse of the two functions above.
// Returns latitude and longitude as two separate scalar functions,
// since DAX UDFs return a single value.
// ---------------------------------------------------------------
DEFINE
/// Destination latitude given a start point, bearing, and distance.
/// @param {NUMERIC} Lat1 - start latitude, decimal degrees
/// @param {NUMERIC} Lon1 - start longitude, decimal degrees
/// @param {NUMERIC} BearingDeg - initial bearing, degrees from true north
/// @param {NUMERIC} DistanceM - distance to travel, metres
/// @returns Destination latitude, decimal degrees
FUNCTION DestinationLat = (
    Lat1 : NUMERIC,
    Lon1 : NUMERIC,
    BearingDeg : NUMERIC,
    DistanceM : NUMERIC
) =>
    VAR EarthRadiusM = 6371000
    VAR Delta = DistanceM / EarthRadiusM
    VAR Theta = RADIANS(BearingDeg)
    VAR Phi1 = RADIANS(Lat1)
    VAR Phi2 = ASIN(SIN(Phi1) * COS(Delta) + COS(Phi1) * SIN(Delta) * COS(Theta))
    RETURN
        DEGREES(Phi2)

/// Destination longitude given a start point, bearing, and distance.
/// @param {NUMERIC} Lat1 - start latitude, decimal degrees
/// @param {NUMERIC} Lon1 - start longitude, decimal degrees
/// @param {NUMERIC} BearingDeg - initial bearing, degrees from true north
/// @param {NUMERIC} DistanceM - distance to travel, metres
/// @returns Destination longitude, decimal degrees
FUNCTION DestinationLon = (
    Lat1 : NUMERIC,
    Lon1 : NUMERIC,
    BearingDeg : NUMERIC,
    DistanceM : NUMERIC
) =>
    VAR EarthRadiusM = 6371000
    VAR Delta = DistanceM / EarthRadiusM
    VAR Theta = RADIANS(BearingDeg)
    VAR Phi1 = RADIANS(Lat1)
    VAR Lambda1 = RADIANS(Lon1)
    VAR Phi2 = ASIN(SIN(Phi1) * COS(Delta) + COS(Phi1) * SIN(Delta) * COS(Theta))
    VAR Lambda2 = Lambda1 + Atan2(
        SIN(Theta) * SIN(Delta) * COS(Phi1),
        COS(Delta) - SIN(Phi1) * SIN(Phi2)
    )
    RETURN
        DEGREES(Lambda2)

EVALUATE
{ DestinationLat(53.4808, -2.2426, 146.03, 261983) }  // should land close to London
EVALUATE
{ DestinationLon(53.4808, -2.2426, 146.03, 261983) }


// ---------------------------------------------------------------
// Practical salinity from conductivity ratio (PSS-78, UNESCO 1981).
// A published, standard formula -- not something we've derived.
// ---------------------------------------------------------------
DEFINE
/// Practical salinity from conductivity ratio, PSS-78 (UNESCO 1981),
/// at atmospheric pressure (no pressure correction term applied).
/// @param {NUMERIC} ConductivityRatio - Rt, conductivity ratio relative to standard seawater at the same temperature
/// @param {NUMERIC} TemperatureC - in-situ temperature, deg C
/// @returns Practical salinity, PSU
FUNCTION PracticalSalinity = (
    ConductivityRatio : NUMERIC,
    TemperatureC : NUMERIC
) =>
    VAR R = ConductivityRatio
    VAR T = TemperatureC
    VAR K = 0.0162
    VAR BaseTerm =
        0.0080
        - 0.1692 * POWER(R, 0.5)
        + 25.3851 * R
        + 14.0941 * POWER(R, 1.5)
        - 7.0261 * POWER(R, 2)
        + 2.7081 * POWER(R, 2.5)
    VAR TempCorrection =
        (T - 15) / (1 + K * (T - 15))
        * (
            0.0005
            - 0.0056 * POWER(R, 0.5)
            - 0.0066 * R
            - 0.0375 * POWER(R, 1.5)
            + 0.0636 * POWER(R, 2)
            - 0.0144 * POWER(R, 2.5)
        )
    RETURN
        BaseTerm + TempCorrection

EVALUATE
{ PracticalSalinity(1.0, 15) }  // R=1.0 at T=15C should return ~35 PSU
